# Generated by Django 5.1.5 on 2025-02-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='movie_app.review'),
        ),
    ]
